AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  SAM Template for products service

Globals:
  Function:
    Runtime: 'python3.9'
    Timeout: 60
    Architectures:
        - x86_64
    Environment:
        Variables:
          POSTGRES_HOST: tinitiate_postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          POSTGRES_USER: tinitiate
          POSTGRES_PASSWORD: tinitiate
          

Resources:

  
  ProductGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev  
      #Auth:
      #  Authorizers:
          #ApiCognitoAuthorizer:
            # type: apiKey
            # name: Authorization
            # in: header
            # x-amazon-apigateway-authtype: cognito_user_pools
            # x-amazon-apigateway-authorizer:
            #   type: cognito_user_pools
            #   providerARNs:
            #     - arn:aws:cognito-idp:{region}:{userpoolIdentifier}
 

  AddToCartFunction:
    Type: 'AWS::Serverless::Function'
    Properties:      
      Handler: 'AddtoCart.add_product'
      #Environment:
        #Variables:
          #AWS_REGION :
          #USERPOOL_ID:
      Layers:
        - !Ref DependencyLayer
      Events:
        ApiPost:
          Type: Api
          Properties:
            RestApiId: !Ref ProductGatewayApi
            Path: /addtocart
            Method: Post  

  UpdateCartFunction:
    Type: 'AWS::Serverless::Function'
    Properties:      
      Handler: 'UpdateCart.update_product'
      Layers:
        - !Ref DependencyLayer
      Events:
        ApiPost:
          Type: Api
          Properties:
            RestApiId: !Ref ProductGatewayApi
            Path: /updatecart
            Method: post

  TransferCartFunction:
    Type: 'AWS::Serverless::Function'
    Properties:      
      Handler: 'TransferCart.transer_cart'
      Layers:
        - !Ref DependencyLayer
      Environment:
        Variables:
          CART_DELETE_SQS_QUEUE: !Ref CartDeleteSQSQueue 
      Events:
        ApiPost:
          Type: Api
          Properties:
            RestApiId: !Ref ProductGatewayApi
            Path: /transfercart
            Method: post
           # Auth:
           #   Authorizer: ApiCognitoAuthorizer
 
  ListCartFunction:
    Type: 'AWS::Serverless::Function'
    Properties:      
      Handler: 'ListCart.list_records'
      Layers:
        - !Ref DependencyLayer
      Events:
        ApiGet:
          Type: Api
          Properties:
            RestApiId: !Ref ProductGatewayApi
            Path: /listcart
            Method: Get

  CheckOutCartFunction:
    Type: 'AWS::Serverless::Function'
    Properties:      
      Handler: 'CheckOutCart.checkout_cart'
      Layers:
        - !Ref DependencyLayer
      Events:
        ApiPost:
          Type: Api
          Properties:
            RestApiId: !Ref ProductGatewayApi
            Path: /checkoutcart
            Method: Post
           # Auth:
           #   Authorizer: ApiCognitoAuthorizer

  DeleteFromCartFunction:
    Type: 'AWS::Serverless::Function'
    Properties:      
      Handler: 'DeleteCart.delete_records'
      Layers:
        - !Ref DependencyLayer
      Events:
        GetFromSQS:
          Type: SQS
          Properties:
            Queue: !GetAtt CartDeleteSQSQueue.Arn
            BatchSize: 5
    
  CartDeleteSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 20
      RedrivePolicy:
        deadLetterTargetArn:
          !GetAtt CartDeleteSQSDLQ.Arn
        maxReceiveCount: 5

  CartDeleteSQSDLQ:
    Type: AWS::SQS::Queue
  
  DependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.9